# Projeto Final - Limpeza e Tratamento de Dados

## Contexto

Uma empresa de e-commerce disponibilizou um arquivo contendo pedidos realizados durante os meses de abril a junho de 2025.

Antes de realizar qualquer análise comercial, a equipe de dados precisa preparar essa base.

Porém, o arquivo apresenta problemas comuns encontrados em dados reais:

 - Clientes sem identificação
 - Cidades escritas em formatos diferentes
 - Status com letras maiúsculas e minúsculas
 - Datas armazenadas como texto
 - Valores monetários inconsistentes
 - Campos obrigatórios vazios

O objetivo será criar uma base limpa e pronta para análise.

## 1. Importação da base

In [92]:
# Bibliotecas

import pandas as pd
import numpy as np

In [93]:
# Leitura do CSV

df = pd.read_csv(
    "vendas.csv"
)

df.head()

,id_pedido,data_pedido,cliente,cidade,estado,produto,categoria,quantidade,valor_unitario,forma_pagamento,status
0,PED0001,15/04/2025,Carlos Oliveira,Blumenau,SC,Notebook Lenovo,Informática,1.0,3499.9,Cartão,Entregue
1,PED0002,18/04/2025,Maria Souza,BLUMENAU,SC,Mouse Logitech,Informática,2.0,89.9,Pix,Entregue
2,PED0003,22/04/2025,João Silva,São Paulo,SP,Monitor LG,Informática,1.0,1299.9,Cartão,Entregue
3,PED0004,25/04/2025,Ana Costa,SAO PAULO,SP,Cadeira Escritório,Móveis,1.0,899.9,Boleto,Entregue
4,PED0005,02/05/2025,Pedro Lima,Curitiba,PR,Teclado Mecânico,Informática,1.0,249.9,Pix,Entregue

## 2. Conhecendo os dados

In [94]:
# Primeiras linhas
df.head()

,id_pedido,data_pedido,cliente,cidade,estado,produto,categoria,quantidade,valor_unitario,forma_pagamento,status
0,PED0001,15/04/2025,Carlos Oliveira,Blumenau,SC,Notebook Lenovo,Informática,1.0,3499.9,Cartão,Entregue
1,PED0002,18/04/2025,Maria Souza,BLUMENAU,SC,Mouse Logitech,Informática,2.0,89.9,Pix,Entregue
2,PED0003,22/04/2025,João Silva,São Paulo,SP,Monitor LG,Informática,1.0,1299.9,Cartão,Entregue
3,PED0004,25/04/2025,Ana Costa,SAO PAULO,SP,Cadeira Escritório,Móveis,1.0,899.9,Boleto,Entregue
4,PED0005,02/05/2025,Pedro Lima,Curitiba,PR,Teclado Mecânico,Informática,1.0,249.9,Pix,Entregue

In [95]:
# Quantidade de linhas e colunas
df.shape

(100, 11)

In [96]:
# Informações
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_pedido        100 non-null    str
 1   data_pedido      100 non-null    str
 2   cliente          98 non-null     str
 3   cidade           100 non-null    str
 4   estado           100 non-null    str
 5   produto          98 non-null     str
 6   categoria        100 non-null    str
 7   quantidade       99 non-null     float64
 8   valor_unitario   100 non-null    float64
 9   forma_pagamento  99 non-null     str
 10  status           100 non-null    str
dtypes: float64(2), str(9)
memory usage: 8.7 KB

In [97]:
# Estatísticas
df.describe()

       quantidade  valor_unitario
count   99.000000      100.000000
mean     1.373737     1646.101000
std      0.763796     1388.826468
min      1.000000       89.900000
25%      1.000000      249.900000
50%      1.000000     1299.900000
75%      1.500000     2799.900000
max      5.000000     3899.900000

## 3. Identificando valores ausentes

### Verificando valores nulos

In [98]:
df.isnull().sum()

id_pedido          0
data_pedido        0
cliente            2
cidade             0
estado             0
produto            2
categoria          0
quantidade         1
valor_unitario     0
forma_pagamento    1
status             0
dtype: int64

### Visualizando registros incompletos

In [99]:
df[df.isnull().any(axis=1)]

,id_pedido,data_pedido,cliente,cidade,estado,produto,categoria,quantidade,valor_unitario,forma_pagamento,status
7,PED0008,12/05/2025,NaN,Curitiba,PR,Notebook Acer,Informática,1.0,3899.9,Cartão,Entregue
8,PED0009,18/05/2025,Fernanda Lima,São Paulo,SP,Smart TV LG,Eletrônicos,1.0,2799.9,NaN,Cancelado
16,PED0017,22/06/2025,Beatriz Souza,Blumenau,SC,NaN,Informática,1.0,150.0,Pix,Entregue
72,PED0073,08/01/2026,NaN,São Paulo,SP,Smart TV LG,Eletrônicos,1.0,2799.9,Boleto,Entregue
73,PED0074,10/01/2026,Beatriz Souza,BLUMENAU,SC,Cadeira Escritório,Móveis,NaN,899.9,Pix,Entregue
74,PED0075,12/01/2026,Rafael Santos,Curitiba,PR,NaN,Informática,1.0,249.9,Cartão,Entregue

## 4. Tratamento de valores ausentes
### Cliente sem identificação

O campo cliente é importante para análises futuras.

Como não sabemos quem realizou o pedido, vamos substituir por:

Cliente Não Identificado

In [100]:
df["cliente"] = df["cliente"].fillna(
    "Cliente Não Identificado"
)

### Forma de pagamento ausente

Neste caso o pedido está cancelado.

Vamos preencher:

Não informado

In [101]:
df["forma_pagamento"] = df["forma_pagamento"].fillna(
    "Não informado"
)

### Produto ausente

In [102]:
df["produto"] = df["produto"].fillna(
    "Produto Não Informado"
)

#### Tratar quantidade vazia

In [103]:
df = df.dropna(
    subset=["quantidade"]
)

## 5. Padronização de textos

In [104]:
df["cidade"] = df["cidade"].str.upper()
df["estado"] = df["estado"].str.upper()
df["status"] = df["status"].str.upper()

## 6. Removendo espaços extras

In [105]:
df["cidade"] = df["cidade"].str.strip()
df["cliente"] = df["cliente"].str.strip()

## 7. Padronizando nomes das cidades

In [106]:
df["cidade"] = (
    df["cidade"]
    .replace(
        {
            "SAO PAULO":"SÃO PAULO"
        }
    )
)

## 8. Conversão de datas

In [107]:
df["data_pedido"] = pd.to_datetime(
    df["data_pedido"],
    dayfirst=True
)

## 9. Tratamento do valor unitário

In [108]:
df["valor_unitario"]

0     3499.9
1       89.9
2     1299.9
3      899.9
4      249.9
       ...
95     199.9
96     249.9
97     899.9
98    3899.9
99    3499.9
Name: valor_unitario, Length: 99, dtype: float64

In [109]:
df["valor_unitario"] = (
    df["valor_unitario"]
    .astype(str)
    .str.replace(",",".")
)

In [110]:
df["valor_unitario"] = pd.to_numeric(
    df["valor_unitario"],
    errors="coerce"
)

## 10. Criando uma coluna de faturamento

In [111]:
df["valor_total"] = (
    df["quantidade"] *
    df["valor_unitario"]
)

In [112]:
# Arredondamento
df["valor_total"] = df["valor_total"].round(2)

In [113]:
# Visualizando
df[
[
"id_pedido",
"produto",
"valor_total"
]
]

   id_pedido             produto  valor_total
0    PED0001     Notebook Lenovo       3499.9
1    PED0002      Mouse Logitech        179.8
2    PED0003          Monitor LG       1299.9
3    PED0004  Cadeira Escritório        899.9
4    PED0005    Teclado Mecânico        249.9
..       ...                 ...          ...
95   PED0096      Fone Bluetooth        399.8
96   PED0097    Teclado Mecânico        249.9
97   PED0098  Cadeira Escritório        899.9
98   PED0099       Notebook Acer       3899.9
99   PED0100     Notebook Lenovo       3499.9

[99 rows x 3 columns]

## 11. Tratando status dos pedidos

In [114]:
df["status"].value_counts()

status
ENTREGUE     95
CANCELADO     4
Name: count, dtype: int64

## 12. Removendo pedidos cancelados

In [115]:
df_vendas = df[
    df["status"]=="ENTREGUE"
]

In [116]:
# Conferindo
df_vendas["status"].unique()

<StringArray>
['ENTREGUE']
Length: 1, dtype: str

## 13. Verificando qualidade final

In [117]:
# Valores ausentes
df_vendas.isnull().sum()

id_pedido          0
data_pedido        0
cliente            0
cidade             0
estado             0
produto            0
categoria          0
quantidade         0
valor_unitario     0
forma_pagamento    0
status             0
valor_total        0
dtype: int64

In [118]:
# Tipos
df_vendas.info()

<class 'pandas.DataFrame'>
Index: 95 entries, 0 to 99
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_pedido        95 non-null     str
 1   data_pedido      95 non-null     datetime64[us]
 2   cliente          95 non-null     str
 3   cidade           95 non-null     str
 4   estado           95 non-null     str
 5   produto          95 non-null     str
 6   categoria        95 non-null     str
 7   quantidade       95 non-null     float64
 8   valor_unitario   95 non-null     float64
 9   forma_pagamento  95 non-null     str
 10  status           95 non-null     str
 11  valor_total      95 non-null     float64
dtypes: datetime64[us](1), float64(3), str(8)
memory usage: 9.6 KB

In [119]:
# Registros iniciais e finais
df_vendas.head()
df_vendas.tail()

,id_pedido,data_pedido,cliente,cidade,estado,produto,categoria,quantidade,valor_unitario,forma_pagamento,status,valor_total
95,PED0096,2026-03-08,Lucas Pereira,SÃO PAULO,SP,Fone Bluetooth,Eletrônicos,2.0,199.9,Boleto,ENTREGUE,399.8
96,PED0097,2026-03-10,Beatriz Souza,CURITIBA,PR,Teclado Mecânico,Informática,1.0,249.9,Cartão,ENTREGUE,249.9
97,PED0098,2026-03-12,Rafael Santos,BLUMENAU,SC,Cadeira Escritório,Móveis,1.0,899.9,Pix,ENTREGUE,899.9
98,PED0099,2026-03-15,Juliana Costa,SÃO PAULO,SP,Notebook Acer,Informática,1.0,3899.9,Cartão,ENTREGUE,3899.9
99,PED0100,2026-03-18,Carlos Oliveira,BLUMENAU,SC,Notebook Lenovo,Informática,1.0,3499.9,Cartão,ENTREGUE,3499.9

## 14. Análise rápida após tratamento

#### Faturamento por cidade

In [120]:
df_vendas.groupby(
    "cidade"
)["valor_total"].sum()

cidade
BLUMENAU     65554.7
CURITIBA     48066.4
SÃO PAULO    47315.8
Name: valor_total, dtype: float64

#### Produtos mais vendidos

In [121]:
df_vendas.groupby(
    "produto"
)["quantidade"].sum().sort_values(
    ascending=False
)

produto
Mouse Logitech           35.0
Fone Bluetooth           19.0
Notebook Lenovo          14.0
Monitor LG               12.0
Cadeira Escritório       12.0
Teclado Mecânico         12.0
Notebook Acer             9.0
Smartphone Samsung        9.0
Smart TV LG               7.0
Produto Não Informado     2.0
Mesa Escritório           1.0
Name: quantidade, dtype: float64

#### Formas de pagamento

In [122]:
df_vendas["forma_pagamento"].value_counts()

forma_pagamento
Cartão    40
Pix       38
Boleto    17
Name: count, dtype: int64

## 15. Exportando a base limpa

In [123]:
df_vendas.to_csv(
    "vendas_tratadas.csv",
    index=False
)